const main = async function() {try {(await new Promise(o => {
try {{}} catch(error) {
}}));
(await new Promise(async (ok, fallo) => {
try {{}} catch(error) {
}}));
return 300;} catch(error) {
return 0;}};